version: "3.9"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./migrate.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  migrations:
    image: migrate/migrate:latest
    entrypoint: ["migrate", "-path", "/migrations", "-database", "postgres://admin:admin@postgres:5432/avito?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - "postgres"

  server:
    depends_on:
      - "postgres"
      - "migrations"
    build:
      context: .
      dockerfile: deployments/Dockerfile
    environment:
      CONFIG_PATH: "/app/configs/config.json"
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
    ports:
      - "80:80"
